### ISSUE TITLE
NPM package is out of date

### ISSUE THREAD

**Issue by adrianso** [EmergingTechnologyAdvisors/node-docker-secrets#3]
The published NPM package is at commit 2b9e51583ee3980050db9a088282927b3acbc839. There are a few useful bug fixes after that.

Can you please update the NPM package please?

**Comment by skinofstars** [comment]
Hi, is there any chance this package is going to get published? Thanks

**Comment by arhea** [comment]
@adrianso / @skinofstars - the new version should now be published to `@cloudreach/docker-secrets`. Let me know if that doesn't work and I will get it updated!

**Comment by arhea** [comment]
Apologies, we updated the naming as we consolidated github orgs.
